# Generated by Django 4.1.3 on 2023-01-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='name',
            field=models.CharField(default=120, max_length=10),
            preserve_default=False,
        ),
    ]
