# Generated by Django 4.1.3 on 2023-01-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
