# Generated by Django 4.1.3 on 2023-01-26 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainstations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trains', '0003_alter_train_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='train',
            name='destination',
        ),
        migrations.AddField(
            model_name='train',
            name='departureStation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure', to='trainstations.trainstation'),
        ),
        migrations.AddField(
            model_name='train',
            name='destinationStation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='trainstations.trainstation'),
        ),
        migrations.AlterField(
            model_name='train',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor', to=settings.AUTH_USER_MODEL),
        ),
    ]
