# Generated by Django 4.1.3 on 2023-02-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainstations', '0003_remove_trainstation_administrator'),
        ('users', '0002_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainstations.trainstation'),
        ),
    ]
