# Generated by Django 4.1.3 on 2023-03-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Station worker', 'Station Worker'), ('Train conductor', 'Train Conductor')], default='Train conductor', max_length=25),
        ),
    ]
