# Generated by Django 4.1.3 on 2023-02-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainstations', '0002_alter_trainstation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainstation',
            name='administrator',
        ),
    ]
